# Generated by Django 2.1.3 on 2018-11-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='flat_number',
            new_name='apartment_number',
        ),
    ]
