# Generated by Django 2.1.3 on 2018-11-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_mail', '0002_auto_20181125_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='building_number',
            field=models.CharField(max_length=50),
        ),
    ]
