# Generated by Django 2.1.3 on 2018-11-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_mail', '0003_auto_20181126_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
